### ISSUE TITLE
Can't import the named export 'ApolloLink' from non EcmaScript module

### ISSUE THREAD

**Issue by pleerock** [jaydenseric/apollo-upload-client#72]
After doing following:

```ts
import {createUploadLink} from "apollo-upload-client";

export const GraphqlClient = new ApolloClient({
    link: createUploadLink({ uri: "http://localhost:3000/graphql" }),
    cache: new InMemoryCache(),
});
```

I have these errors when building using webpack:

```
ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
33:13-23 Can't import the named export 'ApolloLink' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
34:14-23 Can't import the named export 'selectURI' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
43:32-56 Can't import the named export 'selectHttpOptionsAndBody' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
45:8-26 Can't import the named export 'fallbackHttpConfig' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
53:18-41 Can't import the named export 'serializeFetchParameter' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
75:15-25 Can't import the named export 'Observable' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
76:34-57 Can't import the named export 'createSignalIfSupported' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js

ERROR in ./node_modules/apollo-upload-client/lib/index.mjs
88:14-39 Can't import the named export 'parseAndCheckHttpResponse' from non EcmaScript module (only default export is available)
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/service/GraphqlClient.js
 @ ./src/component/AppComponent.js
 @ ./src/index.js
```

Do you have any ideas in mind why I have following errors?

**Comment by pleerock** [comment]
Issue changed, Ive updated

**Comment by pleerock** [comment]
Removing index.mjs file solves the issue, but apparently I cannot do it in real life.

**Comment by pleerock** [comment]
Im using webpack4 btw

**Comment by jaydenseric** [comment]
Yes, this is an issue that intersects a few different things surrounding ESM and `.mjs`. I'll work on this this as soon as I can. The best solution is to PR `apollo-link-http-common` to properly support named imports with `.mjs` files.

**Comment by jaydenseric** [comment]
This should be fixed in [v7.1.0](https://github.com/jaydenseric/apollo-upload-client/releases/tag/v7.1.0).

Note that the lasting solution is for Apollo to support ESM properly, see https://github.com/apollographql/apollo-link/issues/537. In the meantime, Webpack will display harmless, but annoying warnings like these due to our workarounds:

<img width="800" alt="screen shot 2018-03-07 at 1 24 58 pm" src="https://user-images.githubusercontent.com/1754873/37070334-0a2b848e-220b-11e8-9fdc-91962650b05d.png">
<img width="792" alt="screen shot 2018-03-07 at 1 25 14 pm" src="https://user-images.githubusercontent.com/1754873/37070335-0c0f2f44-220b-11e8-91d6-6f96c7316349.png">

**Comment by pcjmfranken** [comment]
It's actually completely failing to comply for me:

```
Failed to compile.

./node_modules/apollo-upload-client/lib/index.mjs
5:17-34 "export 'default' (imported as 'apolloLinkDefault') was not found in 'apollo-link'
 @ ./node_modules/apollo-upload-client/lib/index.mjs
 @ ./src/index.js
 @ multi (webpack)-dev-server/client?http://localhost:8000 webpack/hot/dev-server babel-polyfill ./src
```

**Comment by gopeter** [comment]
Got the same compile error after upgrading to `7.1.0`

**Comment by jaydenseric** [comment]
@pcjmfranken what version of Webpack are you using?

**Comment by pcjmfranken** [comment]
`"webpack": "^3.11.0"`

Relevant parts of index.js

```js
import { createUploadLink } from 'apollo-upload-client'

const apolloUploadClientLink = createUploadLink({
  uri: `${config.serverUrlHttp}/graphql`,
  fetch: unfetch,
  headers: { Authorization: config.authToken }
})

const apolloLinks = split(
  ({ query }) => {
    const { kind, operation } = getMainDefinition(query)
    return kind === 'OperationDefinition' && operation === 'subscription'
  },
  apolloWebSocketLink,
  apolloUploadClientLink,
  apolloHttpLink
)

const apolloClient = new ApolloClient({
  cache: apolloCache,
  link: ApolloLink.from([
    apolloStateLink,
    apolloLinks
  ])
})
```

The above code works with `"apollo-upload-client": "^7.0.0-alpha.4"`

**Comment by shamit6** [comment]
Meanwhile I import index.js file directly:
`import {createUploadLink} from 'apollo-upload-client/lib/index'`

**Comment by tim-soft** [comment]
I also get compilation errors, I'll have to roll it back for now
