### ISSUE TITLE
Typescript support

### ISSUE THREAD

**Issue by Aranir** [jaydenseric/apollo-upload-client#30]
I tried to use the package in a typescript project but received the following errors:

```
node_modules/@types/graphql/subscription/subscribe.d.ts(17,4): error TS2314: Generic type 'AsyncIterator<T, E>' requires 2 type argument(s).
node_modules/@types/graphql/subscription/subscribe.d.ts(29,4): error TS2304: Cannot find name 'AsyncIterable'.
```

Is Typescript support planned?

**Comment by jaydenseric** [comment]
I am not sure what those errors are about, but I have been working on official support for uploads in Apollo and the new [`apollo-fetch-upload`](https://github.com/apollographql/apollo-fetch/tree/master/packages/apollo-fetch-upload) package is written in TypeScript. It works the same way as `apollo-upload-client`, so perhaps you are better of trying it out: https://github.com/apollographql/apollo-fetch/tree/master/packages/apollo-fetch-upload#setup.

**Comment by Aranir** [comment]
thank you for you suggestion.

on the other project I also get type errors. but on`apollo-upload-client` it could be resolved by adding the following to the `tsconfig.json`

```
    "lib": [
      "es5",
      "es6",
      "dom",
      "es2015.core",
      "es2015.collection",
      "es2015.generator",
      "es2015.iterable",
      "es2015.promise",
      "es2015.proxy",
      "es2015.reflect",
      "es2015.symbol",
      "es2015.symbol.wellknown",
      "esnext.asynciterable"
    ]
```

**Comment by DylanVann** [comment]
@jaydenseric Long term will this module be deprecated in favour of `apollo-upload-client`? If so could a note be added to the readme? Thank you

**Comment by DylanVann** [comment]
Actually it seems like `apollo-fetch-upload` no longer works with Apollo 2.0 so maybe it's the reverse.

**Comment by jaydenseric** [comment]
Yes, `apollo-fetch-upload` is a dead project as at the last second `apollo-fetch` was removed from Apollo v2. We should add deprecation notices to those packages.
